// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY4Pz1cQ383tWjUceIxMoQg4swL0Bb2LM',
    appId: '1:538722686749:web:2caac5ea17c7870e7ef3f4',
    messagingSenderId: '538722686749',
    projectId: 'faceattend-5a5ac',
    authDomain: 'faceattend-5a5ac.firebaseapp.com',
    storageBucket: 'faceattend-5a5ac.firebasestorage.app',
    measurementId: 'G-E41KRCLR72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAel_22IPi5OPO7m37Tsaviuh5aiYmSZWg',
    appId: '1:538722686749:android:4ea184d80fd4860f7ef3f4',
    messagingSenderId: '538722686749',
    projectId: 'faceattend-5a5ac',
    storageBucket: 'faceattend-5a5ac.firebasestorage.app',
  );

}